### ISSUE TITLE
colored_prompt duplicates lines on each keypress

### ISSUE THREAD

**Issue by shaicoleman** [plribeiro3000/jazz_fingers#2] opened 2015-02-05 20:43 UTC
The prompt is showing invalid unicode symbols, and duplicates the line on each keypress.

![colored_prompt_issue](https://cloud.githubusercontent.com/assets/127225/6068825/2259c75c-ad77-11e4-9208-7eadc0f7c2e1.png)

Linux Mint 17 (based on Ubuntu 14.04), Blank Rails 4.2.0 project, Ruby 2.2.0 installed from RVM, compiled with Readline 6.3, Gnome Terminal

Turning off colored_prompt fixes these issues

**Comment by plribeiro3000** [comment] 2015-02-05 21:17
Thx for the feedback @shaicoleman. I will take a look at it asap.

**Comment by plribeiro3000** [comment] 2015-02-05 23:33
@shaicoleman Was this text copy/pasted or inputed one by one?

**Comment by shaicoleman** [comment] 2015-02-06 00:12
It happens for both typed and pasted text.

**Comment by plribeiro3000** [comment] 2015-02-06 00:16
I will try to reproduce it. Thanks for your feedback.

**Comment by plribeiro3000** [comment] 2015-02-18 14:38
@shaicoleman I didn't have time to take a deeper look at this bug yet. Perhaps you could try to isolate the source in the meanwhile?

**Comment by hlascelles** [comment] 2015-03-05 12:53
I'm seeing this too, also Mint 17, rbenv 2.1.5.

Where would be a good place to start in the source?

**Comment by plribeiro3000** [comment] 2015-03-05 13:28
Have you guys read [this comment](https://github.com/plribeiro3000/jazz_fingers/blob/master/lib/jazz_fingers.rb#L15-L18)?
Perhaps thats the reason its failing.

If not i suspect the related code is [here](https://github.com/plribeiro3000/jazz_fingers/blob/master/lib/jazz_fingers/railtie.rb#L55-L65).

**Comment by plribeiro3000** [comment] 2015-04-03 03:28
Did you guys manage to check the `readline` installed?

**Comment by plribeiro3000** [comment] 2015-05-30 23:49
Since i could not reproduce the error (in a good manner) and i got no feedback i'm going to close this issue.

FYI i got this behavior some times. And in all of them i did kill the process with a `CTRL + C`. Some of them i didn't even have `jazz_fingers` in my Gemfile so i believe that this issue might be unrelated with the lib until someone got a way to reproduce it properly.

**Closed as completed by plribeiro3000** 2015-05-30 23:49 UTC
